# Training parameters
n_training_episodes: 25000
learning_rate: 0.7

# Evaluation parameters
n_eval_episodes: 100
eval_seed: []

# Environment parameters
max_steps: 99
gamma: 0.95

# Exploration parameters
max_epsilon: 1.0
min_epsilon: 0.05
decay_rate: 0.005

# Save video directory
video_out_dir: "./results/replay_taxi.mp4"